# =========================
# CONFIG FILE FOR GENOMIC POISONING DETECTOR (Minimal for SynCell via CAE & GNN-AE)
# =========================

# === General Settings ===
experiment_name: "syn_cell_detect_quick_v1"
seed: 42
output_base_dir: "outputs" # Unified output directory for logs, models, results

logging:
  level: "INFO" # DEBUG, INFO, WARNING, ERROR
  log_to_file: true
  # log_file_path will be set programmatically, e.g., outputs/logs/run_timestamp.log

# === Data Settings (Primarily for preprocessor input paths if not CLI) ===
# These paths are usually provided via CLI in main.py.
# data:
#   matrix_path: "path/to/your/matrix.mtx"
#   features_path: "path/to/your/features.tsv"
#   barcodes_path: "path/to/your/barcodes.tsv"

# === Preprocessing Settings ===
preprocessing:
  min_genes_per_cell: 100    # Adjusted for potentially sparse data
  min_cells_per_gene: 3
  n_top_genes: 3000         # Number of Highly Variable Genes to select (CRUCIAL)
  n_pca_components: 50      # Final dimension after PCA, input_dim for models
  n_neighbors_graph: 15     # For k-NN graph construction for GNN
  normalize_method: "log1p" # e.g., log1p, cpm
  scale_data: true
  split_ratio: 0.8          # Train/validation split ratio
  random_state: 42

# === Model Global Config ===
# Common settings applied if not overridden in model-specific sections
global_model_config:
  device: "auto"            # "auto", "cuda", "cpu"
  use_mixed_precision: true # For GPU training efficiency
  num_workers: 0            # For DataLoaders (0 for main process on Windows)

# === Model Specific Configurations ===
GNN:  #gnn_ae_config.yaml
  input_dim: 3000
  hidden_dim: 256
  latent_dim: 64
  conv_type: GCN
  dropout: 0.3
  edge_dropout: 0.2
  device: cuda
  loss_weight_recon: 1.0
  detection_threshold: 0.95
  batch_size: 32  # Unused for GNN-AE (processes entire graph)
  epochs: 100
  learning_rate: 0.001
  patience: 20

CAE: #cae_config.yaml
  input_dim: 3000
  hidden_dim: 512
  latent_dim: 64
  contrastive_margin: 1.0
  dropout: 0.2
  device: cuda
  loss_weights:
    recon: 0.7
    contrastive: 0.3
  detection_threshold: 0.95
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  patience: 20

VAE:  #vae_config.yaml
  input_dim: 3000
  hidden_dim: 512
  latent_dim: 64
  dropout: 0.2
  device: cuda
  loss_weights:
    recon: 0.8
    kl: 0.2
  detection_threshold: 0.95
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  patience: 20

DDPM: #ddpm_config.yaml
  input_dim: 3000
  num_timesteps: 1000
  beta_schedule: linear
  beta_start: 0.0001
  beta_end: 0.02
  unet_model_channels: 64
  unet_time_emb_dim: 64
  unet_dropout: 0.1
  detection_timestep: 500
  device: cuda
  detection_threshold: 0.95
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  patience: 20

# === Detection Fusion Strategy (Simplified for CAE & GNN-AE) ===
# This section would be used by your PoisonDetector class
detection_fusion:
  method: "weighted_average"
  # Weights for models active in SynCell detection
  # The keys here should match how models are identified in the detection results
  weights:
    GNNAutoencoder: 0.6      # Example weight
    ContrastiveAutoencoder: 0.4 # Example weight
  final_threshold: 0.5         # Threshold on the fused score