model: ddpm
input_dim: 3000
num_timesteps: 1000
beta_schedule: linear
beta_start: 0.0001
beta_end: 0.02
unet_model_channels: 64
unet_time_emb_dim: 64
unet_dropout: 0.1
detection_timestep: 500
generation_timestep: 200
device: cuda
detection_threshold: 0.95
batch_size: 10000  # Preprocessing batch size
k_neighbors: 5      # For GNN-AE (unused for DDPM)
train_batch_size: 16  # Training batch size
epochs: 100
learning_rate: 0.001
patience: 20